df <- read.csv("GOODBAD.csv", header = TRUE, na.strings = c("","NA","na"))
head(df)
df1 <- read.csv("dm.csv", header = TRUE, na.strings = c("","NA","na"))
head(df1)
sapply(df1,class)
summary(df1)
df1$Children <- factor(df1$Children)
table(df1$Children)
str(df1$Children)
colSums(is.na(df1))
plot(df1$Age,df1$AmountSpent)
df1$Age1 <- ifelse(df1$Age!="Young", "Middle-old",as.character(df1$Age))
df1$Age1 <- as.factor(df1$Age1)
table(df1$Age1)
table(df1$Age)
plot(df1$Gender,df1$AmountSpent)
plot(df1$OwnHome,df1$AmountSpent)
plot(df1$Married,df1$AmountSpent)
plot(df1$Location,df1$AmountSpent)
plot(df1$Salary,df1$AmountSpent)
library(dplyr)
library(ggplot2)
ggplot(df1,aes(x=Salary,y=AmountSpent))+geom_point()+stat_smooth()
plot(df1$Children,df1$AmountSpent)
table(df1$Children)
df1$Children1 <- ifelse(df1$Children==2|df1$Children==3,"2-3",as.character(df1$Children))
df1$Children1 <- as.factor(df1$Children1)
table(df1$Children1)
plot(df1$History,df1$AmountSpent)
mean <- df1%>%group_by(History)%>%summarise(Mean=mean(AmountSpent))
df1$History1 <- ifelse(is.na(df1$History),"Missing", as.character(df1$History))
df1$History1 <- as.factor(df1$History1)
table(df1$History1)
plot(df1$Catalogs,df1$AmountSpent)
table(df1$Catalogs)
df1$Catalogs <- as.factor(df1$Catalogs)

library(outliers)
outlier(df1,opposite = FALSE, logical = FALSE)
chisq.out.test(df1$Age,variance = var(df1$Age),opposite = FALSE)
outlier(df1$Salary)
data(tea)
install.packages("HDoutliers")
library(HDoutliers)
plotHDoutliers(data)
colSums(is.na(df1))
data <- df1[,-c(1,7,8)]
data1 <- dataTrans(data[,-8])
data1 <- as.data.frame(data1)
plot(data1$Age1,data$AmountSpent)
table(data1$Age1)
data1$Age1 <- as.factor(data1$Age1)
summary(data$AmountSpent)
boxplot(data$AmountSpent)

model <- lm(AmountSpent~., data=data[,-8])
summary(model)

# validate assumptions
plot(model$residuals,model$fitted.values)
qqPlot(model$residuals)
qqplot(model$residuals,model$fitted.values)
library(car)
vif(model)
hist(model$residuals)

model2 <- lm(log(AmountSpent)~., data=data[,-8] )
summary(model2)

# validation checks
plot(model2$residuals,model2$fitted.values)
qqplot(model2$residuals,model2$fitted.values)
hist(model2$residuals)
vif(model2)

model3 <- lm(sqrt(AmountSpent)~., data=data[,-8])
summary(model3)

# validation checks
plot(model3$residuals,model3$fitted.values)
par(mfrow=c(1,2))
qqPlot(model3$residuals)
dev.off()
hist(model3$residuals)
vif(model3)

data$Actual <- log(data$AmountSpent)
data$predicted <- model2$fitted.values


ggplot(data, aes(x=Actual,y=predicted))+geom_line()+stat_smooth()
